// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFixtures = `-- name: ListFixtures :many
SELECT
    f.id, f.season, f.gameweek, f.kickoff_time,
    ht.name AS home_team, at.name AS away_team,
    f.home_score, f.away_score, f.finished,
    f.home_difficulty, f.away_difficulty
FROM fixtures f
JOIN team_seasons hts ON hts.id = f.home_team_id
JOIN teams ht ON ht.id = hts.team_id
JOIN team_seasons ats ON ats.id = f.away_team_id
JOIN teams at ON at.id = ats.team_id
WHERE f.season = $1
    AND ($2::int IS NULL OR f.gameweek = $2)
ORDER BY f.gameweek, f.kickoff_time
`

type ListFixturesParams struct {
	Season   string `json:"season"`
	Gameweek *int32 `json:"gameweek"`
}

type ListFixturesRow struct {
	ID             int32              `json:"id"`
	Season         string             `json:"season"`
	Gameweek       *int32             `json:"gameweek"`
	KickoffTime    pgtype.Timestamptz `json:"kickoff_time"`
	HomeTeam       string             `json:"home_team"`
	AwayTeam       string             `json:"away_team"`
	HomeScore      *int32             `json:"home_score"`
	AwayScore      *int32             `json:"away_score"`
	Finished       bool               `json:"finished"`
	HomeDifficulty *int32             `json:"home_difficulty"`
	AwayDifficulty *int32             `json:"away_difficulty"`
}

func (q *Queries) ListFixtures(ctx context.Context, arg ListFixturesParams) ([]ListFixturesRow, error) {
	rows, err := q.db.Query(ctx, listFixtures, arg.Season, arg.Gameweek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFixturesRow
	for rows.Next() {
		var i ListFixturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.Gameweek,
			&i.KickoffTime,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.HomeScore,
			&i.AwayScore,
			&i.Finished,
			&i.HomeDifficulty,
			&i.AwayDifficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
