// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gameweeks.sql

package store

import (
	"context"
)

const currentGameweek = `-- name: CurrentGameweek :one
SELECT
    $1::text AS season,
    COALESCE(MIN(gameweek), 0)::int AS gameweek
FROM fixtures
WHERE season = $1 AND finished = false
`

type CurrentGameweekRow struct {
	Season   string `json:"season"`
	Gameweek int32  `json:"gameweek"`
}

// Earliest not-yet-finished gameweek for a season — the next one a user
// would want predictions for. MIN() always returns exactly one row; when a
// season has no unfinished fixtures left, gameweek is coalesced to 0 as a
// "no upcoming gameweek" sentinel rather than a nullable/scan-failing NULL.
func (q *Queries) CurrentGameweek(ctx context.Context, season string) (CurrentGameweekRow, error) {
	row := q.db.QueryRow(ctx, currentGameweek, season)
	var i CurrentGameweekRow
	err := row.Scan(&i.Season, &i.Gameweek)
	return i, err
}
