// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fixture struct {
	ID             int32              `json:"id"`
	Season         string             `json:"season"`
	FplFixtureCode int32              `json:"fpl_fixture_code"`
	Gameweek       *int32             `json:"gameweek"`
	KickoffTime    pgtype.Timestamptz `json:"kickoff_time"`
	HomeTeamID     int32              `json:"home_team_id"`
	AwayTeamID     int32              `json:"away_team_id"`
	HomeScore      *int32             `json:"home_score"`
	AwayScore      *int32             `json:"away_score"`
	Finished       bool               `json:"finished"`
	HomeDifficulty *int32             `json:"home_difficulty"`
	AwayDifficulty *int32             `json:"away_difficulty"`
}

type IngestionRun struct {
	ID           int32              `json:"id"`
	Source       string             `json:"source"`
	Season       *string            `json:"season"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	RowsLoaded   *int32             `json:"rows_loaded"`
	Status       string             `json:"status"`
	ErrorMessage *string            `json:"error_message"`
}

type ModelRun struct {
	ID              int32              `json:"id"`
	ModelVersion    string             `json:"model_version"`
	TrainedAt       pgtype.Timestamptz `json:"trained_at"`
	TrainingSeasons []byte             `json:"training_seasons"`
	Hyperparams     []byte             `json:"hyperparams"`
	ValidationMae   pgtype.Numeric     `json:"validation_mae"`
	ValidationRmse  pgtype.Numeric     `json:"validation_rmse"`
	Notes           *string            `json:"notes"`
}

type Player struct {
	ID         int32   `json:"id"`
	FplCode    int32   `json:"fpl_code"`
	FirstName  *string `json:"first_name"`
	SecondName *string `json:"second_name"`
	WebName    *string `json:"web_name"`
}

type PlayerCurrentStatus struct {
	ID                       int32              `json:"id"`
	PlayerID                 int32              `json:"player_id"`
	Season                   string             `json:"season"`
	AsOf                     pgtype.Timestamptz `json:"as_of"`
	TeamID                   *int32             `json:"team_id"`
	Position                 *string            `json:"position"`
	NowCost                  *int32             `json:"now_cost"`
	Status                   *string            `json:"status"`
	ChanceOfPlayingThisRound *int32             `json:"chance_of_playing_this_round"`
	ChanceOfPlayingNextRound *int32             `json:"chance_of_playing_next_round"`
	News                     *string            `json:"news"`
	Form                     pgtype.Numeric     `json:"form"`
	SelectedByPercent        pgtype.Numeric     `json:"selected_by_percent"`
	EpThis                   pgtype.Numeric     `json:"ep_this"`
	EpNext                   pgtype.Numeric     `json:"ep_next"`
}

type PlayerGameweekStat struct {
	ID                       int32          `json:"id"`
	PlayerID                 int32          `json:"player_id"`
	Season                   string         `json:"season"`
	Gameweek                 int32          `json:"gameweek"`
	FixtureID                *int32         `json:"fixture_id"`
	TeamID                   *int32         `json:"team_id"`
	OpponentTeamID           *int32         `json:"opponent_team_id"`
	WasHome                  *bool          `json:"was_home"`
	Minutes                  *int32         `json:"minutes"`
	TotalPoints              *int32         `json:"total_points"`
	GoalsScored              *int32         `json:"goals_scored"`
	Assists                  *int32         `json:"assists"`
	CleanSheets              *int32         `json:"clean_sheets"`
	GoalsConceded            *int32         `json:"goals_conceded"`
	OwnGoals                 *int32         `json:"own_goals"`
	PenaltiesSaved           *int32         `json:"penalties_saved"`
	PenaltiesMissed          *int32         `json:"penalties_missed"`
	YellowCards              *int32         `json:"yellow_cards"`
	RedCards                 *int32         `json:"red_cards"`
	Saves                    *int32         `json:"saves"`
	Bonus                    *int32         `json:"bonus"`
	Bps                      *int32         `json:"bps"`
	Influence                pgtype.Numeric `json:"influence"`
	Creativity               pgtype.Numeric `json:"creativity"`
	Threat                   pgtype.Numeric `json:"threat"`
	IctIndex                 pgtype.Numeric `json:"ict_index"`
	Starts                   *int32         `json:"starts"`
	ExpectedGoals            pgtype.Numeric `json:"expected_goals"`
	ExpectedAssists          pgtype.Numeric `json:"expected_assists"`
	ExpectedGoalInvolvements pgtype.Numeric `json:"expected_goal_involvements"`
	ExpectedGoalsConceded    pgtype.Numeric `json:"expected_goals_conceded"`
	DefensiveContribution    *int32         `json:"defensive_contribution"`
	Value                    *int32         `json:"value"`
	Selected                 *int32         `json:"selected"`
	Source                   string         `json:"source"`
}

type PlayerIDMap struct {
	ID              int32              `json:"id"`
	Season          string             `json:"season"`
	SourceElementID int32              `json:"source_element_id"`
	SourceCode      *int32             `json:"source_code"`
	MatchedPlayerID *int32             `json:"matched_player_id"`
	MatchMethod     string             `json:"match_method"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Reviewed        bool               `json:"reviewed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PlayerSeason struct {
	ID                 int32  `json:"id"`
	PlayerID           int32  `json:"player_id"`
	Season             string `json:"season"`
	FplSeasonElementID int32  `json:"fpl_season_element_id"`
	TeamID             int32  `json:"team_id"`
	Position           string `json:"position"`
}

type Prediction struct {
	ID              int32              `json:"id"`
	PlayerID        int32              `json:"player_id"`
	Season          string             `json:"season"`
	Gameweek        int32              `json:"gameweek"`
	PredictedPoints pgtype.Numeric     `json:"predicted_points"`
	ModelVersion    string             `json:"model_version"`
	PredictedAt     pgtype.Timestamptz `json:"predicted_at"`
	Confidence      pgtype.Numeric     `json:"confidence"`
}

type Team struct {
	ID      int32  `json:"id"`
	FplCode int32  `json:"fpl_code"`
	Name    string `json:"name"`
}

type TeamSeason struct {
	ID                  int32  `json:"id"`
	TeamID              int32  `json:"team_id"`
	Season              string `json:"season"`
	FplSeasonTeamID     int32  `json:"fpl_season_team_id"`
	Strength            *int32 `json:"strength"`
	StrengthAttackHome  *int32 `json:"strength_attack_home"`
	StrengthAttackAway  *int32 `json:"strength_attack_away"`
	StrengthDefenceHome *int32 `json:"strength_defence_home"`
	StrengthDefenceAway *int32 `json:"strength_defence_away"`
}
