// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package store

import (
	"context"
)

const getPlayer = `-- name: GetPlayer :one
SELECT id, first_name, second_name, web_name
FROM players
WHERE id = $1
`

type GetPlayerRow struct {
	ID         int32   `json:"id"`
	FirstName  *string `json:"first_name"`
	SecondName *string `json:"second_name"`
	WebName    *string `json:"web_name"`
}

func (q *Queries) GetPlayer(ctx context.Context, id int32) (GetPlayerRow, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.WebName,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, first_name, second_name, web_name
FROM players
ORDER BY second_name
`

type ListPlayersRow struct {
	ID         int32   `json:"id"`
	FirstName  *string `json:"first_name"`
	SecondName *string `json:"second_name"`
	WebName    *string `json:"web_name"`
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.SecondName,
			&i.WebName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
